### ISSUE TITLE
`NodeMixin` class should not access the user class special methods.

### ISSUE THREAD

**Issue by laurent-laporte-pro** [c0fec0de/anytree#110]
The methods of the `NodeMixin` class should not access the user class special methods.

For instance, the user define a `MyNode` class as bellow:

```python
from anytree import NodeMixin


class MyNode(NodeMixin):
    def __init__(self, name, parent=None, children=None):
        super(MyNode, self).__init__()
        self.name = name
        self.parent = parent
        if children:
            self.children = children
```

In this class, the used can implement some special methods, like ``__eq__`` or ``__len__``,
which can have a specific meaning not related to the Tree structure.
A good exemple could be a `NodeMixin` subclass which also implements `collections.abc.Mapping`:

```python
import collections

from anytree import NodeMixin


class MyMapping(NodeMixin, collections.abc.Mapping):
    def __init__(self, name, parent=None, children=None):
        super(MyMapping, self).__init__()
        self.name = name
        self.parent = parent
        if children:
            self.children = children

    def __iter__(self):
        for child in self.children:
            yield child
            for item in child:
                yield item

    def __len__(self):
        return len(list(iter(self)))

    def __getitem__(self, name):
        for child in self:
            if child.name == name:
                return child
        raise KeyError(name)
```

In this example, the `NodeMixin` class shouldn't make any call to `__iter__`, `__len__` or `__getitem__`.

To avoid that, the `NodeMixin` class should respect the following rules:

- Do not compare nodes by value but by reference.
  In other words, the `NodeMixin` class should not use `==` or `!=` but compare nodes with the `id()` function.
  Comparison could be done with the `is` or `is not` operator. Avoid using `in` or `not in`.

- Do not use truth value testing to check if a node is "empty".
  The `NodeMixin` class should not `if node`, `if not node`, `while node` nor `while not node`.
  Instead, it must compare the node with `None` like this: `if node is not None`, `if node is None`,
  `while node is not None` or `while node is None`.

- Do not presume that nodes are hashable.
  The `NodeMixin` class should not store nodes in `set` or `dict`.
  Instead, it can store node IDs using the `id()` function.

Currently, the following unit test fails:

```python
class TestMyMapping(unittest.TestCase):
    def setUp(self):
        super(TestMyMapping, self).setUp()
        self.root1 = MyMapping("root1")
        self.child1 = MyMapping("child1", parent=self.root1)
        self.child2a = MyMapping("child2a", parent=self.child1)
        self.child2b = MyMapping("child2b", parent=self.child1)

    def test_iter(self):
        expected_list = [self.child1, self.child2a, self.child2b]
        for actual, expected in zip(iter(self.root1), expected_list):
            self.assertIs(actual, expected)

    def test_len(self):
        self.assertEqual(len(self.root1), 3)

    def test_getitem(self):
        self.assertIs(self.root1["child1"], self.child1)
        self.assertIs(self.root1["child2a"], self.child2a)
        self.assertIs(self.root1["child2b"], self.child2b)
        with self.assertRaises(KeyError):
            _ = self.root1["missing"]
```

The error is raised in the `setUp` function:

```python
Traceback (most recent call last):
  ...
  File "path/to/anytree/tests/test_node_mapping.py", line 40, in setUp
    self.child2b = MyMapping("child2b", parent=self.child1)
  File "path/to/anytree/tests/test_node_mapping.py", line 12, in __init__
    self.parent = parent
  File "path/to/anytree/anytree/node/nodemixin.py", line 133, in parent
    self.__check_loop(value)
  File "path/to/anytree/anytree/node/nodemixin.py", line 142, in __check_loop
    if self in node.iter_path_reverse():
  File "path/to/lib/_collections_abc.py", line 687, in __eq__
    return dict(self.items()) == dict(other.items())
  File "path/to/lib/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "path/to/anytree/tests/test_node_mapping.py", line 31, in __getitem__
    raise KeyError(name)
KeyError: <test_node_mapping.MyMapping object at ...>
```

**Comment by c0fec0de** [comment]
I found a bug in the pull request. I will add some more testingm before release.

**Comment by c0fec0de** [comment]
Works. Thanks. Will be part of next release 2.8.0
