### ISSUE TITLE
Error installing with python 3.4

### ISSUE THREAD

**Issue by cblegare** [c0fec0de/anytree#12]
Hi!

I have an issue installing anytree on py34 (also 3.3, but I don't think it is supported) in a virtualenv using tox.

```
Collecting anytree (from pymenu==0.1.0)
  Downloading anytree-2.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q22xz5l_/anytree/setup.py", line 24, in <module>
        config = _read_metainfo("anytree/__init__.py")
      File "/tmp/pip-build-q22xz5l_/anytree/setup.py", line 18, in _read_metainfo
        match = pat.match(line)
    TypeError: can't use a string pattern on a bytes-like object
```

You can see it on my travis build:

https://travis-ci.org/cblegare/pymenu/jobs/239447205

**Comment by c0fec0de** [comment]
Please try anytree 2.2.1. 
Hopefully the bug is fixed. I cannot try it out within my build.

**Comment by cblegare** [comment]
Thanks you @c0fec0de.  9b2d021 did the trick!
