### ISSUE TITLE
Resolver.glob returns IndexError where Resolver.get does not

### ISSUE THREAD

**Issue by zegervdv** [c0fec0de/anytree#125]
Example:

``` python
from anytree import Node
top = Node("top", parent=None)
sub0 = Node("sub0", parent=top)
sub0sub0 = Node("sub0sub0", parent=sub0)
sub0sub1 = Node("sub0sub1", parent=sub0)
sub1 = Node("sub1", parent=top)

from anytree import Resolver
r = Resolver('name')
```

Getting the top node from `sub0`:
```
>>> r.get(sub0, '..')
Node('/top')
```

Using glob:
```
>>> r.glob(sub0, '..')
.../anytree/resolver.py in __glob(self, node, parts)
    165     def __glob(self, node, parts):
    166         nodes = []
--> 167         name = parts[0]
    168         remainder = parts[1:]
    169         # handle relative

IndexError: list index out of range
```

**Comment by c0fec0de** [comment]
Good catch. This is a bug. I will fix it. Will be fixed in 1.8.1

**Comment by zegervdv** [comment]
Great! Just tested with the fix and it works.

**Comment by MHendricks** [comment]
This issue seems to be back in 2.8.0 for the original relative case and when directly referencing the top node.

```python
from anytree import Node, Resolver
top = Node("top", parent=None)
sub0 = Node("sub0", parent=top)
r = Resolver('name')
```

For sub0
```python
>>> print(r.get(sub0, '..'))
Node('/top')
>>> print(r.glob(sub0, '..'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\anytree\resolver.py", line 147, in glob
    return self.__glob(node, parts)
  File "C:\Program Files\Python37\lib\site-packages\anytree\resolver.py", line 171, in __glob
    nodes += self.__glob(node.parent, remainder)
  File "C:\Program Files\Python37\lib\site-packages\anytree\resolver.py", line 167, in __glob
    name = parts[0]
IndexError: list index out of range
```

Referencing the top level in the glob.
```python
>>> print(r.get(top, '/top'))
Node('/top')
>>> print(r.glob(top, '/top'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\anytree\resolver.py", line 147, in glob
    return self.__glob(node, parts)
  File "C:\Program Files\Python37\lib\site-packages\anytree\resolver.py", line 167, in __glob
    name = parts[0]
IndexError: list index out of range
```

**Comment by zegervdv** [comment]
It hasn't been released yet. The 1.8.1 above was a typo.

**Comment by c0fec0de** [comment]
Will release 3.0.0 soon
