### ISSUE TITLE
Unpickling a tree containing a SymlinkNode causes a RecursionError

### ISSUE THREAD

**Issue by btwahl** [c0fec0de/anytree#138]
For context, I'm attempting to use `pickle` instead of the exporters provided by `anytree` because I have some objects that are not JSON serializable. The following is a simple example that duplicates the issue I am experiencing.

Pickling and unpickling a tree that does not contain any `SymlinkNode` nodes does not cause any issues and works as expected:

```python
import pickle
from anytree import Node, SymlinkNode, RenderTree

root = Node(name='root')
a = Node(name='a', parent=root)
b = Node(name='b', parent=a)
# c = SymlinkNode(target=b, parent=a)

for pre, _, node in RenderTree(root):
    print(f'{pre}{node.name}')

with open('testtest.pkl', 'wb') as f:
    pickle.dump(root, f)

with open('testtest.pkl', 'rb') as f:
    root = pickle.load(f)

for pre, _, node in RenderTree(root):
    print(f'{pre}{node.name}')
```

As expected, output is:
```
root
└── a
    └── b
root
└── a
    └── b
```

However, once a SymlinkNode is introduced, there is a RecursionError:

```python
import pickle
from anytree import Node, SymlinkNode, RenderTree

root = Node(name='root')
a = Node(name='a', parent=root)
b = Node(name='b', parent=a)
c = SymlinkNode(target=b, parent=a)

for pre, _, node in RenderTree(root):
    print(f'{pre}{node.name}')

with open('testtest.pkl', 'wb') as f:
    pickle.dump(root, f)

with open('testtest.pkl', 'rb') as f:
    root = pickle.load(f)

for pre, _, node in RenderTree(root):
    print(f'{pre}{node.name}')
```

Now, output is:
```
root
└── a
    ├── b
    └── b
Traceback (most recent call last):
  File "c:/Users/b/Documents/repos/test_space/test.py", line 18, in <module>
    root = pickle.load(f)
  File "C:\Users\b\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anytree\node\symlinknodemixin.py", line 52, in __getattr__      
    return getattr(self.target, name)
  File "C:\Users\b\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anytree\node\symlinknodemixin.py", line 52, in __getattr__      
    return getattr(self.target, name)
  File "C:\Users\b\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anytree\node\symlinknodemixin.py", line 52, in __getattr__      
    return getattr(self.target, name)
  [Previous line repeated 329 more times]
  File "C:\Users\b\AppData\Local\Programs\Python\Python36-32\lib\site-packages\anytree\node\symlinknodemixin.py", line 49, in __getattr__
    if name in ('_NodeMixin__parent', '_NodeMixin__children'):
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by c0fec0de** [comment]
i will take care

physhics <notifications@github.com> schrieb am Mo., 13. Juli 2020, 00:09:

**Comment by kylewhite21** [comment]
Can be fixed by adding an `elif` block to the method [here](https://github.com/c0fec0de/anytree/blob/d63289b65644c6e8c9c1d83d339c2c235d9ecc31/anytree/node/symlinknodemixin.py#L48):
```
    def __getattr__(self, name):
        if name in ('_NodeMixin__parent', '_NodeMixin__children'):
            return super(SymlinkNodeMixin, self).__getattr__(name)
        elif name == '__setstate__':
            raise AttributeError(name)
        else:
            return getattr(self.target, name)
```
