### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by abhiitsaboutme** [c0fec0de/anytree#156]
Hi,
Executing the below code give file not found error

```
from anytree import Node, RenderTree
from anytree.exporter import DotExport
from anytree.dotexport import RenderTr
ceo = Node("CEO") #root
vp_1 = Node("VP_1", parent=ceo)
vp_2 = Node("VP_2", parent=ceo)
gm_1 = Node("GM_1", parent=vp_1)
gm_2 = Node("GM_2", parent=vp_2)
m_1 = Node("M_1", parent=gm_2)
DotExporter(ceo).to_picture("ceo.png")
```

Errorlog:
PS C:\pyhton> & c:/python39/python.exe "c:/pyhton/X/dependencyDatabase/grap-test.py"
Traceback (most recent call last):
  File "c:\pyhton\X\dependencyDatabase\grap-test.py", line 10, in <module>
    DotExporter(ceo).to_picture("ceo.dot")
  File "C:\python39\lib\site-packages\anytree\exporter\dotexporter.py", line 272, in to_picture
    check_call(cmd)
  File "C:\python39\lib\subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by teauxfu** [comment]
for anyone else with this issue, the problem is probably not having installed [graphviz](https://graphviz.org/download/)

**Comment by c0fec0de** [comment]
Yes. Please check your graphviz installation
