### ISSUE TITLE
assert isinstance(data, dict) error

### ISSUE THREAD

**Issue by wsw70** [c0fec0de/anytree#211]
I am trying to load JSON data formatted as in the [documentation ](https://anytree.readthedocs.io/en/latest/importer/jsonimporter.html) and end up with 

```text
Traceback (most recent call last):
  File "d:\dev-pro\searchad\addm123.py", line 10, in <module>
    root = importer.import_(data)
  File "C:\Python310\lib\site-packages\anytree\importer\dictimporter.py", line 38, in import_
    return self.__import(data)
  File "C:\Python310\lib\site-packages\anytree\importer\dictimporter.py", line 47, in __import
    self.__import(child, parent=node)
  File "C:\Python310\lib\site-packages\anytree\importer\dictimporter.py", line 47, in __import
    self.__import(child, parent=node)
  File "C:\Python310\lib\site-packages\anytree\importer\dictimporter.py", line 47, in __import
    self.__import(child, parent=node)
  [Previous line repeated 5 more times]
  File "C:\Python310\lib\site-packages\anytree\importer\dictimporter.py", line 41, in __import
    assert isinstance(data, dict)
AssertionError
```

What does it mean, or more precisely - what kind of data can raise it?

~~I have empty children entries (`"children": []`), is this allowed? (just an idea of where the issue could come from)~~ removing `"children"` entries when empty does not change the issue.

**Comment by c0fec0de** [comment]
Just checked the example. It works.

Feel free to re-open the ticket with your exact code.
