### ISSUE TITLE
RenderTreeGraph(tree).to_picture("test.png") Error: permission denied

### ISSUE THREAD

**Issue by jhaerig** [c0fec0de/anytree#268]
Found a problem when trying to use RenderTreeGraph on a tree structure.
```python
>>> anytree.__version__
'2.12.1'
```

```python
from anytree import Node, RenderTree
from anytree.dotexport import RenderTreeGraph
tree = Node("root")
b = Node("Branch1", parent=tree)
c = Node("Branch2", parent=tree)
d = Node("SubBranch1",parent=c)
e = Node("SubBranch2",parent=c)
RenderTreeGraph(tree).to_picture("tree.png")
```

**Error**
```python
Error: dot: can't open C:\Users\<user>\AppData\Local\Temp\tmpzb2ruk5a: Permission denied
Traceback (most recent call last):
  File "C:\Users\<user>\Desktop\PythonScripts\anytree_test.py", line 8, in <module>
    RenderTreeGraph(tree).to_picture("tree.png")
  File "C:\Python39\lib\site-packages\anytree\exporter\dotexporter.py", line 308, in to_picture
    check_call(cmd)
  File "C:\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dot', 'C:\\Users\\<user>\\AppData\\Local\\Temp\\tmpzb2ruk5a', '-T', 'png', '-o', 'tree.png']' returned non-zero exit status 2
```

I found the reason for that issue in: https://github.com/c0fec0de/anytree/blob/65a5d09ce0a592a80918f094ec3fa48b7faca250/anytree/exporter/dotexporter.py#L302C1-L308C28

**Current**
```Python
with NamedTemporaryFile("wb", delete=False) as dotfile:
	dotfilename = dotfile.name
	for line in self:
		dotfile.write(("%s\n" % line).encode("utf-8"))
	dotfile.flush()
	cmd = ["dot", dotfilename, "-T", fileformat, "-o", filename]
	check_call(cmd)
```
**Should be**
```Python
with NamedTemporaryFile("wb", delete=False) as dotfile:
	dotfilename = dotfile.name
	for line in self:
		dotfile.write(("%s\n" % line).encode("utf-8"))
	dotfile.flush()
cmd = ["dot", dotfilename, "-T", fileformat, "-o", filename]
check_call(cmd)
```

**Comment by sattopadhyay** [comment]
I just checked, this fix works perfectly. I am on Windows 11 and python version 3.12.8
I made a venv in a blank folder with 
`python -m venv .env` 

and wrote the basic script to generate a tree in `write_tree.py` -
```py
from anytree import Node
from anytree.exporter import DotExporter

root = Node("root")
s0 = Node("sub0", parent=root)
s0b = Node("sub0B", parent=s0)
s0a = Node("sub0A", parent=s0)
s1 = Node("sub1", parent=root)
s1a = Node("sub1A", parent=s1)
s1b = Node("sub1B", parent=s1)
s1c = Node("sub1C", parent=s1)
s1ca = Node("sub1Ca", parent=s1c)
DotExporter(root).to_picture("tree.png")
```
then I opened up powershell(ver 7.4.6) and ran
`(.env) PS D:\Documents\coding\tmp\anytree_changes> python .\write_tree.py`

which gave me the usual error output - 
```ps
Error: dot: can't open C:\Users\SOUMYA~1\AppData\Local\Temp\tmpub9lc4f3: Permission denied
Traceback (most recent call last):
  File "D:\Documents\coding\tmp\anytree_changes\write_tree.py", line 13, in <module>
    DotExporter(root).to_picture("tree.png")
  File "D:\Documents\coding\tmp\anytree_changes\.env\Lib\site-packages\anytree\exporter\dotexporter.py", line 308, in to_picture
    check_call(cmd)
  File "C:\Users\Soumyadeep\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dot', 'C:\\Users\\SOUMYA~1\\AppData\\Local\\Temp\\tmpub9lc4f3', '-T', 'png', '-o', 'tree.png']' returned non-zero exit status 2.
```
So I am in favour of this change being incorporated into the project.

Then I opened up `.env\Lib\site-packages\anytree\exporter\dotexporter.py` went to line 307 and made the exact changes mentioned above. Running this file gave no output in the terminal and `tree.png` was successfully generated-

![Image](https://github.com/user-attachments/assets/7e587791-a655-486d-a591-2fa218d692a1)

**Comment by Perseus333** [comment]
https://github.com/c0fec0de/anytree/issues/268#issue-2588707815

I was about to go insane finding the issue. This also fixes the issue for me!
