### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by zodiac911** [c0fec0de/anytree#39]
I want to use anytree in anaconda in Win10 OS, but when i just run 
```python
root = Node("root")
s0 = Node("sub0", parent=root)
s0b = Node("sub0B", parent=s0)
s0a = Node("sub0A", parent=s0)
s1 = Node("sub1", parent=root)
s1a = Node("sub1A", parent=s1)
s1b = Node("sub1B", parent=s1)
s1c = Node("sub1C", parent=s1)
s1ca = Node("sub1Ca", parent=s1c)


RenderTreeGraph(root).to_picture("tree.png")
```

I get error like this
```
runfile('C:/Users/NWPU/.spyder-py3/temp.py', wdir='C:/Users/NWPU/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-12-2380dbac90f7>", line 1, in <module>
    runfile('C:/Users/NWPU/.spyder-py3/temp.py', wdir='C:/Users/NWPU/.spyder-py3')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/NWPU/.spyder-py3/temp.py", line 42, in <module>
    RenderTreeGraph(root).to_picture("tree.png")

  File "C:\ProgramData\Anaconda3\lib\site-packages\anytree\exporter\dotexporter.py", line 229, in to_picture
    check_call(cmd)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 209, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

could somebody help me out?

**Comment by c0fec0de** [comment]
Hi,

graphviz is missing in your installation. Please ensure to have the `graphviz` package installed in your conda environment. Please run:

    conda install graphviz

or create a conda environment with graphviz included.

HTH

**Comment by zodiac911** [comment]
Hi，
I followed your instruction, But I still have a little problem with it, 
here is what I get 
```python
Traceback (most recent call last):

  File "<ipython-input-3-83ed9b3c2fc5>", line 1, in <module>
    runfile('C:/Users/NWPU/Pictures/Work Repository/python_gep/python_gep.py', wdir='C:/Users/NWPU/Pictures/Work Repository/python_gep')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/NWPU/Pictures/Work Repository/python_gep/python_gep.py", line 75, in <module>
    DotExporter(mynode).to_picture("udo.png")

  File "C:\ProgramData\Anaconda3\lib\site-packages\anytree\exporter\dotexporter.py", line 229, in to_picture
    check_call(cmd)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 209, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg

TypeError: argument of type 'bool' is not iterable
```

**Comment by c0fec0de** [comment]
Can you add a minimal example please?

**Comment by NoYo25** [comment]
I have the same error even after installing graphviz==0.14

**Comment by victorterancas** [comment]
I install also graphviz and still have the error.
