### ISSUE TITLE
Installation issue on Python 3.5.2

### ISSUE THREAD

**Issue by bottydim** [c0fec0de/anytree#40]
Could be an anaconda bug or something, this is the output I get:

Collecting anytree
  Downloading anytree-2.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pwc646vg/anytree/setup.py", line 6, in <module>
        from setuptools import setup
    ImportError: cannot import name 'setup'

For Python

**Comment by bottydim** [comment]
Turns out this is due to some faulty setuptools modification. The issues is easily resolved by:
`pip3 install --upgrade pip setuptools wheel`
