### ISSUE TITLE
global name 'findall' is not defined

### ISSUE THREAD

**Issue by kevinfachreza** [c0fec0de/anytree#41]
I got an error findall not defined. i already import Ascii
and im using Python 2.7
here is my code

```
from anytree import Node, RenderTree, AsciiStyle, LevelOrderIter

def buildTree(dataset):
	root = Node("root")

	for data in dataset:
		parent = 0;
		for item in data:
			if parent==0:
				parent = root

			findall(parent, filter_=lambda node: node.name in ("a", "b"))	
			parent = Node(item, parent=parent, support = 1)

	for pre, fill, node in RenderTree(root):
		print("%s%s" % (pre, node.name))
```

here is the error

```
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\AqeelaTugasAkhir\index.py", line 83, in <module>
    tree = buildTree(itemOrdered)
  File "C:\Users\Kevin\PycharmProjects\AqeelaTugasAkhir\index.py", line 60, in buildTree
    findall(parent, filter_=lambda node: node.name in ("a", "b"))
NameError: global name 'findall' is not defined
```

What's wrong with findall?
thanks for help

**Comment by c0fec0de** [comment]
Holdio,

please add findall to the import statement in the first line.

HTH

**Comment by kevinfachreza** [comment]
Its Working! 
I got another error, it was working, but now its wasn't

```
Traceback (most recent call last):
File "anytree.py", line 1, in <module>
from anytree import node, rendertree
File "C:\Python27\anytree.py", line 1, in <module>
from anytree import Node, RenderTree
ImportError: cannot import name Node
```

why does any class from anytree can't be imported?

**Comment by kevinfachreza** [comment]
Its Working!
Thanks
