### ISSUE TITLE
AttributeError when node name is an int

### ISSUE THREAD

**Issue by matthiasbe** [c0fec0de/anytree#95]
Hi,

Thank you for this project, it's really helpful.

I don't know if this is a known issue or if it's written somewhere in the docs, so forgive me if this is misplaced.

I've run into an issue with the following code:
```python
from anytree import Node
from anytree.exporter import DotExporter

root = Node(1)
s0 = Node("sub0", parent=root)
s0b = Node("sub0B", parent=s0)

DotExporter(root).to_dotfile("tree.dot")
```

It gives the following output:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    DotExporter(root).to_dotfile("tree.dot")
  File "/usr/local/lib/python3.7/site-packages/anytree/exporter/dotexporter.py", line 214, in to_dotfile
    for line in self:
  File "/usr/local/lib/python3.7/site-packages/anytree/exporter/dotexporter.py", line 160, in __iter
    for node in self.__iter_nodes(indent, nodenamefunc, nodeattrfunc):
  File "/usr/local/lib/python3.7/site-packages/anytree/exporter/dotexporter.py", line 177, in __iter_nodes
    yield '%s"%s"%s;' % (indent, DotExporter.esc(nodename), nodeattr)
  File "/usr/local/lib/python3.7/site-packages/anytree/exporter/dotexporter.py", line 242, in esc
    return str.replace("\"", "\\\"")
AttributeError: 'int' object has no attribute 'replace'
```

But with the line `root = Node(1)`replaced with `root = Node('1')` it's ok.

Note there is no error when `root` from my example has no child.

**Comment by c0fec0de** [comment]
Duplicate #97. Fixed.
